service virtio_net_mmio
{
	uid	0;
	type	net;
	descr   "Virtio MMIO network device";
	ipc	SYSTEM pm rs ds vm vfs lwip;
	system
		UMAP
		VUMAP
		DEVIO
		IRQCTL
		PRIVCTL
	;
	vm	BASIC;
	irq	1 2 3 4 5 6 7 8;
	io	0x10001000:0x10008000;
}
